# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f76cd7dc296c215b039eb5716176ab43363626331c41a05a2453b4f305d13bc034176801751413f6a3a93a81114fb871d233c4631f74422e3db17980be9558cd

test:
  secret_key_base: 5bece219ecfe254cb622d544cf9b61135a58dbcf0b750c7385cc9e05d286012ade40c0cd2824cb82b252c8957242f11b56e6d010ee825c01dd87a5d16037e6df

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
